using Yaeger.Input;

namespace Yaeger.Browser;

/// <summary>
/// Maps engine <see cref="Keys"/> to DOM <c>KeyboardEvent.code</c> values (physical key
/// positions, layout-independent). Mirrors the native <c>KeyMapper</c>: keys that have several
/// physical variants (Shift, Control, keypad +/-, ...) list every code that should count.
/// </summary>
public static class BrowserKeyMapper
{
    private static readonly Dictionary<Keys, string[]> CodeMap = new()
    {
        [Keys.A] = ["KeyA"],
        [Keys.B] = ["KeyB"],
        [Keys.C] = ["KeyC"],
        [Keys.D] = ["KeyD"],
        [Keys.E] = ["KeyE"],
        [Keys.F] = ["KeyF"],
        [Keys.G] = ["KeyG"],
        [Keys.H] = ["KeyH"],
        [Keys.I] = ["KeyI"],
        [Keys.J] = ["KeyJ"],
        [Keys.K] = ["KeyK"],
        [Keys.L] = ["KeyL"],
        [Keys.M] = ["KeyM"],
        [Keys.N] = ["KeyN"],
        [Keys.O] = ["KeyO"],
        [Keys.P] = ["KeyP"],
        [Keys.Q] = ["KeyQ"],
        [Keys.R] = ["KeyR"],
        [Keys.S] = ["KeyS"],
        [Keys.T] = ["KeyT"],
        [Keys.U] = ["KeyU"],
        [Keys.V] = ["KeyV"],
        [Keys.W] = ["KeyW"],
        [Keys.X] = ["KeyX"],
        [Keys.Y] = ["KeyY"],
        [Keys.Z] = ["KeyZ"],
        [Keys.Num0] = ["Digit0"],
        [Keys.Num1] = ["Digit1"],
        [Keys.Num2] = ["Digit2"],
        [Keys.Num3] = ["Digit3"],
        [Keys.Num4] = ["Digit4"],
        [Keys.Num5] = ["Digit5"],
        [Keys.Num6] = ["Digit6"],
        [Keys.Num7] = ["Digit7"],
        [Keys.Num8] = ["Digit8"],
        [Keys.Num9] = ["Digit9"],
        [Keys.Space] = ["Space"],
        [Keys.Escape] = ["Escape"],
        [Keys.Up] = ["ArrowUp"],
        [Keys.Down] = ["ArrowDown"],
        [Keys.Left] = ["ArrowLeft"],
        [Keys.Right] = ["ArrowRight"],
        [Keys.F1] = ["F1"],
        [Keys.F2] = ["F2"],
        [Keys.F3] = ["F3"],
        [Keys.F4] = ["F4"],
        [Keys.F5] = ["F5"],
        [Keys.F6] = ["F6"],
        [Keys.F7] = ["F7"],
        [Keys.F8] = ["F8"],
        [Keys.F9] = ["F9"],
        [Keys.F10] = ["F10"],
        [Keys.F11] = ["F11"],
        [Keys.F12] = ["F12"],
        [Keys.Plus] = ["Equal", "NumpadAdd"],
        [Keys.Minus] = ["Minus", "NumpadSubtract"],
        [Keys.Shift] = ["ShiftLeft", "ShiftRight"],
        [Keys.Control] = ["ControlLeft", "ControlRight"],
        [Keys.Alt] = ["AltLeft", "AltRight"],
        [Keys.Super] = ["MetaLeft", "MetaRight"],
        [Keys.LeftBracket] = ["BracketLeft"],
        [Keys.RightBracket] = ["BracketRight"],
        [Keys.Tab] = ["Tab"],
        [Keys.Enter] = ["Enter"],
        [Keys.Backspace] = ["Backspace"],
        [Keys.Delete] = ["Delete"],
        [Keys.Insert] = ["Insert"],
        [Keys.Home] = ["Home"],
        [Keys.End] = ["End"],
        [Keys.PageUp] = ["PageUp"],
        [Keys.PageDown] = ["PageDown"],
        [Keys.Comma] = ["Comma"],
        [Keys.Period] = ["Period"],
        [Keys.Slash] = ["Slash"],
        [Keys.Semicolon] = ["Semicolon"],
        [Keys.CapsLock] = ["CapsLock"],
        [Keys.NumLock] = ["NumLock"],
        [Keys.ScrollLock] = ["ScrollLock"],
        [Keys.PrintScreen] = ["PrintScreen"],
        [Keys.Pause] = ["Pause"],
        [Keys.Backslash] = ["Backslash"],
        [Keys.Apostrophe] = ["Quote"],
        [Keys.GraveAccent] = ["Backquote"],
        [Keys.Menu] = ["ContextMenu"],
        [Keys.Keypad0] = ["Numpad0"],
        [Keys.Keypad1] = ["Numpad1"],
        [Keys.Keypad2] = ["Numpad2"],
        [Keys.Keypad3] = ["Numpad3"],
        [Keys.Keypad4] = ["Numpad4"],
        [Keys.Keypad5] = ["Numpad5"],
        [Keys.Keypad6] = ["Numpad6"],
        [Keys.Keypad7] = ["Numpad7"],
        [Keys.Keypad8] = ["Numpad8"],
        [Keys.Keypad9] = ["Numpad9"],
        [Keys.KeypadDecimal] = ["NumpadDecimal"],
        [Keys.KeypadDivide] = ["NumpadDivide"],
        [Keys.KeypadMultiply] = ["NumpadMultiply"],
        [Keys.KeypadEnter] = ["NumpadEnter"],
    };

    /// <summary>Every DOM code that counts as <paramref name="key"/> being held; empty if unmapped.</summary>
    public static IReadOnlyList<string> GetDomCodes(Keys key) =>
        CodeMap.TryGetValue(key, out var codes) ? codes : [];
}
