using System.Numerics;
using Yaeger.ECS;
using Yaeger.Graphics;
using Yaeger.Physics.Components;
using Yaeger.Systems;

namespace Yaeger.Physics.Systems;

/// <summary>
/// Integrates velocity into position and rotation using semi-implicit Euler integration.
/// Also applies linear drag.
/// </summary>
/// <remarks>
/// A dynamic entity that also carries a <see cref="BoxCollider2D"/> has its planned
/// displacement swept against every solid (non-trigger, non-one-way) <see cref="BoxCollider2D"/>
/// obstacle that isn't itself a dynamic body — a static platform, or one generated by
/// <see cref="TilemapColliderSystem"/> — via <see cref="SweptAabb"/>. This stops a fast body
/// from tunneling clean through a thin obstacle within a single step: displacement is clamped to
/// just past the earliest contact instead of landing wherever the naive
/// <c>position + velocity * deltaTime</c> would put it, so this step's discrete
/// <see cref="CollisionDetectionSystem"/> pass always finds a small genuine overlap to resolve
/// normally. Circle colliders, triggers, and one-way platforms are not swept — out of scope for
/// this pass (see <c>docs/physics.md</c>). Candidate obstacles are queried brute-force each call
/// (no broadphase) — adequate for typical level sizes; revisit if profiling shows otherwise.
/// </remarks>
public class MovementSystem(World world) : IUpdateSystem
{
    /// <summary>
    /// Small absolute overshoot (world units) applied past a swept contact's entry time, so this
    /// step's discrete narrowphase detects a small genuine overlap and
    /// <see cref="CollisionResolutionSystem"/> resolves the contact with its usual impulse and
    /// positional correction — instead of the body resting exactly at zero penetration with its
    /// velocity untouched.
    /// </summary>
    private const float ContactOvershoot = 0.001f;

    private readonly List<(Entity Entity, BoxCollider2D Collider, Vector2 Center)> _obstacles = [];

    public void Update(float deltaTime)
    {
        RefreshObstacles();

        // Query enumerates RigidBody2D store; we only write back Transform2D and Velocity2D,
        // so no snapshot needed — iterating a different store than we're mutating.
        foreach (
            (
                Entity entity,
                RigidBody2D body,
                Transform2D transform,
                Velocity2D velocity
            ) in world.Query<RigidBody2D, Transform2D, Velocity2D>()
        )
        {
            if (body.Type == BodyType.Static)
                continue;

            var newVelocity = velocity;

            // Apply linear drag to dynamic bodies
            if (body.Type == BodyType.Dynamic && body.LinearDrag > 0)
            {
                var dragFactor = 1.0f - body.LinearDrag * deltaTime;
                if (dragFactor < 0.0f)
                {
                    dragFactor = 0.0f;
                }
                newVelocity.Linear *= dragFactor;
            }

            var displacement = newVelocity.Linear * deltaTime;

            if (
                body.Type == BodyType.Dynamic
                && _obstacles.Count > 0
                && world.TryGetComponent<BoxCollider2D>(entity, out var moverCollider)
            )
            {
                displacement = ClampAgainstTunneling(
                    entity,
                    moverCollider,
                    transform.Position + moverCollider.Offset,
                    displacement
                );
            }

            // Integrate position and rotation
            var newTransform = transform;
            newTransform.Position += displacement;
            newTransform.Rotation += newVelocity.Angular * deltaTime;

            world.AddComponent(entity, newTransform);
            world.AddComponent(entity, newVelocity);
        }
    }

    private void RefreshObstacles()
    {
        _obstacles.Clear();

        foreach (
            (Entity entity, BoxCollider2D collider, Transform2D transform) in world.Query<
                BoxCollider2D,
                Transform2D
            >()
        )
        {
            if (collider.IsTrigger || collider.OneWay)
                continue;
            if (
                world.TryGetComponent<RigidBody2D>(entity, out var body)
                && body.Type == BodyType.Dynamic
            )
                continue;

            _obstacles.Add((entity, collider, transform.Position + collider.Offset));
        }
    }

    private Vector2 ClampAgainstTunneling(
        Entity mover,
        BoxCollider2D moverCollider,
        Vector2 start,
        Vector2 displacement
    )
    {
        if (displacement == Vector2.Zero)
            return displacement;

        var halfSize = moverCollider.HalfSize;
        var earliestT = 1f;
        var hit = false;

        foreach (var (obstacleEntity, obstacleCollider, obstacleCenter) in _obstacles)
        {
            if (obstacleEntity == mover)
                continue;
            if (
                !ShouldCollide(
                    moverCollider.Layer,
                    moverCollider.CollidesWith,
                    obstacleCollider.Layer,
                    obstacleCollider.CollidesWith
                )
            )
                continue;

            if (
                SweptAabb.TryGetEntryFraction(
                    start,
                    halfSize,
                    displacement,
                    obstacleCenter,
                    obstacleCollider.HalfSize,
                    out var t
                )
                && t < earliestT
            )
            {
                earliestT = t;
                hit = true;
            }
        }

        if (!hit)
            return displacement;

        // Nudge slightly past the contact time by a fixed absolute distance (not a fraction of
        // the full displacement) so an extreme velocity can't itself overshoot past a thin
        // obstacle's far side.
        var displacementLength = displacement.Length();
        if (displacementLength < 1e-10f)
            return displacement * earliestT;

        var overshootT = MathF.Min(ContactOvershoot / displacementLength, 1f - earliestT);
        return displacement * (earliestT + overshootT);
    }

    private static bool ShouldCollide(
        int layerA,
        uint collidesWithA,
        int layerB,
        uint collidesWithB
    ) => (collidesWithA & (1u << layerB)) != 0 && (collidesWithB & (1u << layerA)) != 0;
}
