using Silk.NET.Input;

namespace Yaeger.Input;

public static class KeyMapper
{
    private static readonly Dictionary<Key, Keys> KeyMap = new()
    {
        { Key.W, Keys.W },
        { Key.A, Keys.A },
        { Key.S, Keys.S },
        { Key.D, Keys.D },
        { Key.Q, Keys.Q },
        { Key.E, Keys.E },
        { Key.Space, Keys.Space },
        { Key.Escape, Keys.Escape },
        { Key.Up, Keys.Up },
        { Key.Down, Keys.Down },
        { Key.Left, Keys.Left },
        { Key.Right, Keys.Right },
        { Key.R, Keys.R },
        { Key.I, Keys.I },
        { Key.J, Keys.J },
        { Key.H, Keys.H },
        { Key.Number1, Keys.Num1 },
        { Key.Number2, Keys.Num2 },
        { Key.Number3, Keys.Num3 },
        { Key.Number4, Keys.Num4 },
        { Key.C, Keys.C },
        { Key.F1, Keys.F1 },
        { Key.B, Keys.B },
        { Key.V, Keys.V },
        { Key.P, Keys.P },
        { Key.T, Keys.T },
        { Key.O, Keys.O },
        { Key.Equal, Keys.Plus },
        { Key.KeypadAdd, Keys.Plus },
        { Key.Minus, Keys.Minus },
        { Key.KeypadSubtract, Keys.Minus },
        { Key.M, Keys.M },
        { Key.ShiftLeft, Keys.Shift },
        { Key.ShiftRight, Keys.Shift },
        { Key.F, Keys.F },
        { Key.LeftBracket, Keys.LeftBracket },
        { Key.RightBracket, Keys.RightBracket },
        { Key.Number0, Keys.Num0 },
        { Key.Number5, Keys.Num5 },
        { Key.Number6, Keys.Num6 },
        { Key.Number7, Keys.Num7 },
        { Key.Number8, Keys.Num8 },
        { Key.Number9, Keys.Num9 },
        { Key.G, Keys.G },
        { Key.K, Keys.K },
        { Key.L, Keys.L },
        { Key.N, Keys.N },
        { Key.U, Keys.U },
        { Key.X, Keys.X },
        { Key.Y, Keys.Y },
        { Key.Z, Keys.Z },
        { Key.F2, Keys.F2 },
        { Key.F3, Keys.F3 },
        { Key.F4, Keys.F4 },
        { Key.F5, Keys.F5 },
        { Key.F6, Keys.F6 },
        { Key.F7, Keys.F7 },
        { Key.F8, Keys.F8 },
        { Key.F9, Keys.F9 },
        { Key.F10, Keys.F10 },
        { Key.F11, Keys.F11 },
        { Key.F12, Keys.F12 },
        { Key.Tab, Keys.Tab },
        { Key.Enter, Keys.Enter },
        { Key.Backspace, Keys.Backspace },
        { Key.Delete, Keys.Delete },
        { Key.Insert, Keys.Insert },
        { Key.Home, Keys.Home },
        { Key.End, Keys.End },
        { Key.PageUp, Keys.PageUp },
        { Key.PageDown, Keys.PageDown },
        { Key.ControlLeft, Keys.Control },
        { Key.ControlRight, Keys.Control },
        { Key.AltLeft, Keys.Alt },
        { Key.AltRight, Keys.Alt },
        { Key.SuperLeft, Keys.Super },
        { Key.SuperRight, Keys.Super },
        { Key.Comma, Keys.Comma },
        { Key.Period, Keys.Period },
        { Key.Slash, Keys.Slash },
        { Key.BackSlash, Keys.Backslash },
        { Key.Semicolon, Keys.Semicolon },
        { Key.Apostrophe, Keys.Apostrophe },
        { Key.GraveAccent, Keys.GraveAccent },
        { Key.CapsLock, Keys.CapsLock },
        { Key.NumLock, Keys.NumLock },
        { Key.ScrollLock, Keys.ScrollLock },
        { Key.PrintScreen, Keys.PrintScreen },
        { Key.Pause, Keys.Pause },
        { Key.Menu, Keys.Menu },
        { Key.Keypad0, Keys.Keypad0 },
        { Key.Keypad1, Keys.Keypad1 },
        { Key.Keypad2, Keys.Keypad2 },
        { Key.Keypad3, Keys.Keypad3 },
        { Key.Keypad4, Keys.Keypad4 },
        { Key.Keypad5, Keys.Keypad5 },
        { Key.Keypad6, Keys.Keypad6 },
        { Key.Keypad7, Keys.Keypad7 },
        { Key.Keypad8, Keys.Keypad8 },
        { Key.Keypad9, Keys.Keypad9 },
        { Key.KeypadDecimal, Keys.KeypadDecimal },
        { Key.KeypadDivide, Keys.KeypadDivide },
        { Key.KeypadMultiply, Keys.KeypadMultiply },
        { Key.KeypadEnter, Keys.KeypadEnter },
    };

    public static bool TryGetMappedKey(Key key, out Keys mappedKey) =>
        KeyMap.TryGetValue(key, out mappedKey);
}
