namespace Yaeger.Rendering;

/// <summary>
/// Shared unit-cube geometry (36 vertices, 12 triangles, CCW winding viewed from outside) used
/// wherever cube vertex positions double as cubemap sample directions: <see cref="SkyboxRenderer"/>
/// draws it from inside to render the sky, and <see cref="IblPrefilter"/> draws it from inside once
/// per capture direction to render each face of a prefiltered cubemap.
/// </summary>
internal static class UnitCubeGeometry
{
    public static readonly float[] Vertices =
    [
        // back (-Z)
        -1f,
        1f,
        -1f,
        -1f,
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        1f,
        1f,
        -1f,
        -1f,
        1f,
        -1f,
        // left (-X)
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        1f,
        1f,
        -1f,
        -1f,
        1f,
        // right (+X)
        1f,
        -1f,
        -1f,
        1f,
        -1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        -1f,
        1f,
        -1f,
        -1f,
        // front (+Z)
        -1f,
        -1f,
        1f,
        -1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        -1f,
        1f,
        -1f,
        -1f,
        1f,
        // top (+Y)
        -1f,
        1f,
        -1f,
        1f,
        1f,
        -1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        1f,
        -1f,
        1f,
        1f,
        -1f,
        1f,
        -1f,
        // bottom (-Y)
        -1f,
        -1f,
        -1f,
        -1f,
        -1f,
        1f,
        1f,
        -1f,
        -1f,
        1f,
        -1f,
        -1f,
        -1f,
        -1f,
        1f,
        1f,
        -1f,
        1f,
    ];
}
